version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/docker-compose
    overwrite: yes
permissions:
  - object: /home/ec2-user/docker-compose
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: afterInstall.sh
      timeout: 180
      runas: ec2-user